spring.application.name=webgis-poc-backend
server.port=8092

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/lulc_db
spring.datasource.username=aakashsrivastava
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =================================================================
# THIRD-PARTY GIS API KEYS & GOOGLE EARTH ENGINE CREDENTIALS
# =================================================================

# 1. OpenWeatherMap API Key
openweathermap.apikey=

# 2. Google Earth Engine Settings
google.earth.engine.project=
google.earth.engine.credentials.path=

# 3. data.gov.in API Configuration
datagovin.apikey=579b464db66ec23bdd000001cea920c661994101610f17c1c193a02a
datagovin.resource.soilmoisture=20e844f2-d146-43d2-b8b6-a9b1f6e10ca8
datagovin.resource.drinkingwater=de1d093e-1436-4f83-a32f-11aede7e9f06
datagovin.resource.commodityprices=35985678-0d79-46b4-9ed6-6f13308a1d24
datagovin.resource.aqi=3b01bcb8-0b14-4abf-b6f2-c1bfd384ba69
datagovin.resource.population=463d908b-c03b-47d3-b5bb-33d584d27f65

# 4. Gemini API Configuration
gemini.api.key=${GEMINI_API_KEY}
